### ISSUE TITLE
GSL locally

### ISSUE THREAD

**Issue by pinghanchu** [drjuls/AMBiT#18]
Hi, the default GSL library (at /usr/include/gsl/) is too old in my group cluster so that I installed the latest one in my home. However, I could not figure out the correct path in config.ini for GSL. Anyway I can setup the link? Thanks.

**Comment by emilyviolet** [comment]
Hi Pinghan,

You’re correct in that there is not a field for GSL in the config file - I’ll add one as soon as I can. In the meantime, you should be able to manually specifying the compilation and linking options in config.ini. via the “Lib path” and “Include path” fields.

When you compile/install GSL, there should be two key components: a directory of header files (usually
something like gsl/<files>) and a compiled library called libgsl.so. Can you try adding the following flags to your config.ini 

Lib path=/path/to/library
Include path=/path/to/headers

This should force SCons and your compiler to look in the directory where you installed gsl, rather than trying to guess.

Thanks,

Emily

**Comment by pinghanchu** [comment]
Thanks, Emily. 
Here is my config.ini:
-----------------------------------------------
[AMBiT options]
AMBiT path = /home/pchu/proj/Software/local/ambit
Angular data =

[Dependency paths]
Lib path = -I/home/pchu/proj/Software/local/gsl/lib
Include path = -I/home/pchu/proj/AMBiT -I/home/pchu/proj/Software/local/gsl/include
Eigen path = /home/pchu/proj/Software/local/eigen/include/eigen3
Sparsehash path = /home/pchu/proj/Software/local/sparsehash/include
gtest lib path =
gtest header path =

[Dependencies]
; These libraries will be linked with -l<lib> flags by the linker                                                                                                        
Libs = gsl,
       lapack,
       blas,
       boost_system,
       boost_filesystem
-------------------------

Here is the message I got after scons
-------------------------
scons: Reading SConscript files ...
Angular data directory not specified. Defaulting to /home/pchu/proj/Software/local/ambit
Checking pkg-config version... (cached) yes
Checking whether the C++ compiler works... (cached) yes
Checking whether gfortran program exists.../usr/bin/gfortran
Checking for C library gsl... (cached) yes
Checking for C library lapack... (cached) yes
Checking for C library blas... (cached) yes
Checking for C++ header file boost/version.hpp... (cached) yes
Checking gsl is at least version 2.0...(cached) no
Checking eigen3 is at least version 3.2.0...(cached) yes
Finished configuring build environment.

scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.
--------------------------------

It seems it still cannot find out gsl
"Checking gsl is at least version 2.0...(cached) no"

Could you help me to figure out the issue?

Thanks,

pinghan

**Comment by pinghanchu** [comment]
Hi Emily,
Here is the config.log. Thanks
'https://gist.github.com/pinghanchu/ca91657c185b40f3ea138ebd37ef30b1

pinghan

**Comment by emilyviolet** [comment]
Hi Pinghan,

This appears to be a problem with how SCons checks which version of GSL is installed. This is probably going to cause issues with other people who install GSL from source, so I have pushed a patch to the `master` branch removing those checks until I can find a better solution. Can you grab the latest patch from the `master` branch (through either a `git pull` or by manually downloading the new `SConstruct` file) and try compiling again?

Thanks,

Emily

**Comment by emilyviolet** [comment]
Hi Pinghan,

I'm glad that sorted out one of the problems. About sparsehash: sparsehash only requires the header files to be included, so there's no .so library to link against. This makes including it in the SCons checks difficult to do for a number of technical reasons. Thank you for finding this problem though - I'll see if I can do anything to alleviate it.

I am slightly confused about the steps you took to get the second error message you posted. It looks as if you issued the `make` command after running `scons`? This could be the cause of the problem, if that is indeed what you are doing. SCons actually builds the program for you as well as configuring the build environment, so you do not need to run `make` at all - just let `scons` do its thing and see if that works. We include the Makefiles for legacy systems without SCons but do not recommend you use them if you have SCons available. I also can't provide support for the Makefiles since they are so machine specific and have almost no automation or checks built in.

Additionally, if `scons` runs into the same problem, double check that your Sparsehash directory (Software/local/sparsehash/include) contains a folder called "sparsehash", which in turn includes the "sparse_hash_map" and "dense_hash_map" header files. This is the default directory structure from doing the standard `./configure && make && make install` process on Linux (provided you obtained sparsehash from their github repository https://github.com/sparsehash/sparsehash), but it may be different depending on how you installed sparsehash. If you do not have the `sparsehash/sparse_hash_map` directory structure, you may have to fiddle around with renaming directories (or the `./configure` options when install Sparsehash)  to get it to work. This is an unfortunate complication that comes with installing Sparsehash from source and there's not a lot we can do about it.

I hope these help get things going smoothly.

Thanks,

Emily

**Comment by emilyviolet** [comment]
Yep, that looks fine to me. You should hopefully have an executable file
called “ambit” in your install directory now; try running it with “./ambit
-h” and if you see a help message printed to the terminal then you should
be good to go.

Emily

**Comment by pinghanchu** [comment]
Great. Thanks. I found "ambit".
I will  learn how to use this code.

Thanks,
pinghan
